### ISSUE TITLE
没有进行刷票

### ISSUE THREAD

**Issue by qisiqisi** [shenh10/trainticket_booker#5]
您好，我在使用时可登录，但登录后在cmd输入c，没有进行刷票，希望得到您的帮助，谢谢，以下是部分输出信息。
////////////////////////////以下是输出信息//////////////////////////////
DevTools listening on ws://127.0.0.1:12598/devtools/browser/308198b8-749f-4696-8cd3-f88d71ff8225 exception on 广州!
exception on 南宁东!
宸叉墦寮€闊充箰鎻愰啋
[3768:3472:0112/153605.306:ERROR:service_manager.cc(157)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
--Return--
> d:\eclipse-workspace\trainticket_booker\crawler.py(139)login()->None
-> pdb.set_trace()
(Pdb)
 
////////////////配置文件//////////////
[new 1.txt](https://github.com/shenh10/trainticket_booker/files/1625274/new.1.txt)

**Comment by shenh10** [comment]
是否确保进入了欢迎登录界面？需要进入登录界面再按c

**Comment by qisiqisi** [comment]
是的，这是输入c后的输出信息

Try 1 times
date: 2018-02-09, from 广州, to 南宁东
Traceback (most recent call last):
  File "crawler.py", line 320, in <module>
    ticket_theif.executor()
  File "crawler.py", line 270, in executor
    this_train = self.checkTicket(date, fromStation, toStation)
  File "crawler.py", line 161, in checkTicket
    self.b.add_cookie({'name': '_jc_save_fromStation', 'value': self.station[fromStation]})
  File "D:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 872, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "D:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: missing 'value'
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

**Comment by bumblebeehub** [comment]
我也是同样的错误

**Comment by bumblebeehub** [comment]
我查了一下说selenium的chromedriver版本要和chrome的版本对应，于是我重新下了chromedriver版本，结果还是一样的，不知道是不是selenium版本错误（我的chrome版本为v63，driver版本为v2.34，selenium版本为最新版）
